### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by russellkim** [eugeneyan/recsys-nlp-graph#1]
Hi! Your blog post and notebook codes are amazing!
Could you let me know where I get the data used in your notebook codes?

Is the following info correct ?
"Small" subsets for experimentation in https://nijianmo.github.io/amazon/index.html

Thanks!

**Comment by eugeneyan** [comment]
Thanks for your kind words. I got it from Professor Julian McAuley, Associate Professor at UC San Diego. 

More details here: https://eugeneyan.com/2020/01/06/recommender-systems-baseline-pytorch/#data-acquisition
