### ISSUE TITLE
Can I have a brief instruction on how to execute those codes?

### ISSUE THREAD

**Issue by myeonghak** [eugeneyan/recsys-nlp-graph#5]
Hi Yan, Thank you again for sharing this awesome work.

Several months after translating & sharing your great post into my language with your kind approval (https://myeonghak.github.io/graph%20neural%20networks/recommender%20systems/RecSys-Beating-the-baseline-recommender-using-Graph-and-NLP-techniques-in-PyTorch/), 

I am reviewing your code work to reproduce your work on my own dataset.

but I have no idea where to start, which program should be run first etc.

could you give us any kind of brief instruction commands to try on my own, with amazon dataset that you used?

thanks.

regards,

Mattias

**Comment by eugeneyan** [comment]
Hey Mattias, 

Thanks for taking at interest in this poorly documented codebase 🤣 

Perhaps you might find the steps in this [shell script](https://github.com/eugeneyan/recsys-nlp-graph/blob/master/run.sh) helpful?

**Comment by myeonghak** [comment]
Oh my, I feel almost shameful for me not to check that shell script.

Thank you so much for reminding, and for this brilliant job! 

hope you have a good day! 👍🏼
